default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: schedule_mailer_development
  username: <%= ENV["USERNAME_DATABASE"] %>
  password: <%= ENV["PASSWORD_DATABASE"] %>

test:
  <<: *default
  database: schedule_mailer_test
  username: <%= ENV["USERNAME_DATABASE"] %>
  password: <%= ENV["PASSWORD_DATABASE"] %>

production:
  <<: *default
  database: schedule_mailer_production
  username: <%= ENV["USERNAME_DATABASE"] %>
  password: <%= ENV["schedule_mailer_PASSWORD"] %>
